# VOIDDESK XFCE - Xorg su framebuffer (RG35XX-H / muOS)
Section "Device"
    Identifier "FBDEV"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "FBDEV"
EndSection

Section "ServerFlags"
    Option "AutoAddGPU" "false"
    Option "DontVTSwitch" "true"
    Option "AllowEmptyInput" "false"
EndSection

Section "InputClass"
    Identifier "evdev-all"
    MatchDevicePath "/dev/input/event*"
    Driver "evdev"
EndSection
